import Head from 'next/head'
import Header from './components/header'
import New_Section from './components/new_section'
import Best_Sellers from './components/best_sellers'
import Edits_Section from './components/edits_section'
import Notice_Section from './components/notice_section'
import Bottom_Menu from './components/bottom_menu'
import Mobile_Header from './components/mobile_header'
import styled from 'styled-components'

export default function Home() {
  return (
    <>
      <Head>
        <title>Function. | Job Test</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="https://function.london/apple-touch-icon.png" />
      </Head>
    <HomePageWrapper>
      <Header />
      <Mobile_Header />
      <New_Section />
      <Best_Sellers />
      <Edits_Section />
      <Notice_Section />
      <Bottom_Menu />
    </HomePageWrapper>
    </>
  )
}

const HomePageWrapper = styled.main`
overflow-x: hidden;`
